version: '3.7'
services:
  dev_api:
    build: .
    container_name: molu_dev_api
    environment:
      - TZ=Asia/Seoul
      - server.profile=dev
      - db.url=jdbc:mysql://db/molu
      - db.username=root
      - db.password=password
    ports:
      - 8080:8080

networks:
  default:
    external:
      name: dev_net